### ISSUE TITLE
Add login section to the nav

### ISSUE THREAD

**Issue by dachic** [iw-dak/spreading#17]

**Comment by kconde2** [comment]
![20190627_004858](https://user-images.githubusercontent.com/43377621/60220233-a8acc000-9875-11e9-8d1e-e483c6f57a17.jpg)

**Comment by kconde2** [comment]
![header-with-login-and-search](https://user-images.githubusercontent.com/43377621/60220332-f5909680-9875-11e9-9c7e-5a8520124503.jpg)

**Comment by DrissBelaroussi** [comment]
Done
